---
title: "NOPD"
author: "Grady Keene"
---

```{r}
#Appropriate packages
library(tidyverse)
library(readr)
library(summarytools)
library(gtsummary)
```

```{r}
#Retrieved from New Orleans Police Department
nopd <- read_csv("C:/Users/grady/Downloads/NOPD.csv")

#Binary variable if firearm was used
nopd %>% 
  mutate(Firearm_Or_Not = ifelse(grepl("Firearm", Use.of.Force.Type),1,0)) -> nopdh1
#Select relevant variables
nopdh1 %>%
  select(Firearm_Or_Not, Date.Occurred, solo_or_not, Shift, Officer.Race.Ethnicity, Officer.Gender, Officer.Age, Use.of.Force.Type, Officer.Years.of.Service) -> nopdh1

#Filter to include only individual officers and create binary variable for gender of officer and categorical for Race/Ethnicity
nopdh1 %>% 
  filter(solo_or_not == "Individual") %>%
  mutate(Officer.Gender = recode(Officer.Gender,
                                 "Male" = "1",
                                 "Female" = "0"),
        Officer.Race.Ethnicity.cat = recode(Officer.Race.Ethnicity,
                                          "White" = "1",
                                          "Black" = "2",
                                         "Hispanic" = "3",
                                         "Asian/Pacific" = "4",
                                          "Unknown" = "5")) %>%
  na.omit() -> nopdh1

#Omit NA values or statistically insignificant observations and create new data frame where race/ethnicity is a factor
nopdh1 %>%
  filter(!Officer.Race.Ethnicity.cat == "Indigenous") %>%
  mutate(Officer.Race.Ethnicity = as.factor(Officer.Race.Ethnicity.cat),
         Officer.Gender = as.numeric(Officer.Gender),
         Officer.Age = as.numeric(Officer.Age),
         Officer.Years.of.Service = as.numeric(Officer.Years.of.Service))-> nopd_h1
```

```{r}
#Summary statistics
mean(nopd_h1$Firearm_Or_Not)
mean(nopd_h1$Officer.Gender, na.rm = TRUE)
mean(nopd_h1$Officer.Age)
sd(nopd_h1$Officer.Age)
mean(nopd_h1$Officer.Years.of.Service)
sd(nopd_h1$Officer.Years.of.Service)


#Visualize distributions 
library(ggiraph)
library(ggformula)
ggplot(nopdh1, aes(Officer.Race.Ethnicity)) +
  geom_bar(aes(y = (..count..)/sum(..count..)), color = "black", fill = "red") +
  scale_y_continuous(labels = percent) +
  xlab("Officer's Race/Ethnicity") +
  ylab("Percent") +
  theme_bw()

ggplot(nopd_h1, aes(Officer.Age)) +
  geom_bar(color = "black", fill = "white") +
  xlab("Officer Age") +
  ylab("Count") +
  theme_bw()


ggplot(nopd_h1, aes(Officer.Years.of.Service, stat="count")) +
  geom_histogram(bins = 20, color = "black", fill = "white") +
  xlab("Officer Years of Service") +
  ylab("Count") +
  theme_bw()

library(summarytools)
ctable(nopd_h1$Officer.Race.Ethnicity, nopd_h1$Firearm_Or_Not, prop = "r", chisq = TRUE, headings = FALSE)

```

```{r}
#Using variables Officer.Years.of.Service, Officer.Gender,  and Officer.Age to predict use of a firearm through logistic regression returns

fit <- glm(Firearm_Or_Not ~ Officer.Gender + Officer.Age + Officer.Years.of.Service, family = binomial("logit"), data = nopd_h1) 
summary(fit)

#logit[P(y=1)] = -0.614 + 0.31Male + 0.007Age - 0.016Years.of.Service

```

```{r}
MASS::stepAIC(fit, trace = FALSE)
#Using stepwise regression to select the strongest model with the same variables returns: Firearm_Or_Not ~ Officer.Gender is best where AIC decreases from 1308 to 1305.
```


```{r}
firearm <- glm(Firearm_Or_Not ~ Officer.Gender, family = binomial("logit"), data = nopd_h1)
summary(firearm)

#logit[P(y=1)] = -0.49 + 0.30Male
#Since 0.3 > 0, if an officer is male, the probability of using/presenting a firearm increases.
```

```{r}
#For a **male** officer:

(exp(-0.49+.3))/(1 + exp(-0.49+.3))

#The estimated probability for using/presenting a firearm is 0.453
```

```{r}
#For a **female** officer:

(exp(-0.49))/(1 + exp(-0.49))

#The estimated probability for using/presenting a firearm is 0.38
```

```{r}
#Visualize the logistic regression
model1 <- glm(Firearm_Or_Not ~ Officer.Gender + as.numeric(Officer.Years.of.Service), family = binomial("logit"), data = nopd_h1)
summary(model1)

plotting_dfm <- expand.grid(Officer.Years.of.Service = seq(from = 0, to = 75, by = 1),
                            Officer.Gender = (0:1))
plotting_dfm$preds <- plogis(predict(model1, newdata = plotting_dfm))

ggplot(plotting_dfm, aes(Officer.Years.of.Service, y = preds, color = as.factor(Officer.Gender))) +
  geom_line() +
  ggtitle("Predicted Use of Firearm by Years of Service and Gender") +
  ylab("Predicted Firearm Use") + 
  xlab("Years of Service") +
  theme_bw()
```



